image: node:14-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /node_modules/

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  script:
    - echo "Hello!"
    - npm install
    - ls

api-test:
  stage: test
  tags:
    - docker
  script:
    - npm run test

mqtt-test:
  stage: test
  tags:
    - docker
  script:
  - echo "This will test the MQTT client"